export enum QueryKeys {
  CURRENT_EMPLOYEE = 'currentEmployee',
  CATEGORIES = 'categories',
  PRODUCTS = 'products',
  CUSTOMERS = 'customers',
  STORE_PRODUCTS = 'storeProducts',
  EMPLOYEES = 'employees',
  RECEIPTS = 'receipts',
  RECEIPT_TOTAL_SUM = 'receiptTotalSum',
  RECEIPT_SOLD_PRODUCTS = 'receiptSoldProducts',
  MY_RECENT_RECEIPTS = 'myRecentReceipts',
  EMPLOYEES_NO_HIGH_DISCOUNT_CLIENTS = 'employeesNoHighestDiscountClients',
  RECEIPT_SUMMARY_BY_CATEGORIES = 'receiptSummaryByCategories',
  NOT_SOLD_PRODUCTS = 'notSoldProducts',
}
